### ISSUE TITLE
entities become unavailable after update to 1.0.9

### ISSUE THREAD

**Issue by SamDeZwam** [bertouttier/flukso-hacs#10]
Hi,

After updating to 1.0.9 via HACS I have the same problem as I had earlier this week when I manually copied the changed files to the custom_components/flukso folder on my homeassistant.
The entities become unavailable.
This is what I see on my dashboard:  " This entity is no longer being provided by the flukso integration. If the entity is no longer in use, delete it in settings. "

I deleted the integration and added it again. This worked fine, but no new entities were added.
I rolled back to 1.0.8 and everything worked again (including the warning about the MQTT syntax)

Regards,
Sam

**Comment by bertouttier** [comment]
Hi @SamDeZwam
Could you show us a screenshot of the Flukso integration on the integrations page? [Here](https://my.home-assistant.io/redirect/_change/?redirect=config_flow_start%2F%3Fdomain%3Dflukso) is a link to help you get there if you have the "my homesssistant" integration enabled. 

Kind regards

**Comment by SamDeZwam** [comment]
Hi,

These are screenshots with* 1.0.8 active*

Dashboard:

[image: image.png]

Integration:

[image: image.png]

Device:

[image: image.png]

Entities

[image: image.png]

[image: image.png]


With *1.0.9 installed:*

Dashboard:

[image: image.png]
[image: image.png]


Integration

[image: image.png]


Device

[image: image.png]

Entities

[image: image.png]


The warning about the repair is gone.

Kind regards,
Sam




Op do 6 okt. 2022 om 18:53 schreef Bert Outtier ***@***.***>:

**Comment by SamDeZwam** [comment]
Hi,

Some extra info:

When I rollback to 1.0.8 using a copied directory from earlier, everything
is OK after a restart of home assistant. (the way I did the last days)
When I rollback using HACS, Redownload version 1.0.8, the entities remain
unavailable. (just tried)

Regards,
Sam

Op do 6 okt. 2022 om 19:13 schreef Sam Lowie ***@***.***>:

**Comment by vk2him** [comment]
1.0.9 working fine for me

@SamDeZwam - your screenshots didn't work ...

**Comment by SamDeZwam** [comment]
Hi,

These are screenshots with 1.0.8 active

Dashboard:
![image](https://user-images.githubusercontent.com/98612553/194508777-56a3a595-6b37-4eb1-9b3b-44c9224bd981.png)
Integration:
![image](https://user-images.githubusercontent.com/98612553/194508808-f2820a3b-a71b-47e3-9531-5584c34bffd2.png)
Device:
![image](https://user-images.githubusercontent.com/98612553/194508849-5cfa7db1-3884-4345-a177-f87bd29be849.png)
Entities
![image](https://user-images.githubusercontent.com/98612553/194508871-7adaf4bc-3f21-4d62-84e0-826068b91934.png)

![image](https://user-images.githubusercontent.com/98612553/194508908-9fd382f0-4620-4ffb-95a2-e5326db22551.png)

With 1.0.9 installed:

Dashboard:
![image](https://user-images.githubusercontent.com/98612553/194508935-5a10bc97-1c92-4d42-b6cf-c3e3beffb97f.png)
![image](https://user-images.githubusercontent.com/98612553/194508972-81986006-af61-4d1b-835a-57c8d6d308cc.png)


Integration
![image](https://user-images.githubusercontent.com/98612553/194508999-a9aaffe1-5f0d-49b0-a3b2-100d966a4762.png)

Device
![image](https://user-images.githubusercontent.com/98612553/194509023-b7093525-888e-4345-a93d-b1ee4c6e3efb.png)
Entities
![image](https://user-images.githubusercontent.com/98612553/194508724-0bd57c3a-5dc3-4fdb-aad5-cb8b75d96ad9.png)

The warning about the repair is gone.

Kind regards,
Sam

**Comment by giecie** [comment]
I have exactly the same results and screenshots after upgrading to 1.0.9 and had also to revert back to 1.0.8.

**Comment by bertouttier** [comment]
Hello all,

To understand what is going on, could you enable debug logs and send them? Enabling debug logs can be done by adding the following to your configuration.yaml:
```
logger:
  default: error
  logs:
    custom_components.flukso: debug
```
And could you also post the output of the following MQTT topics?
```
/device/+/test/tap
/device/+/config/+
```
Please use your HA broker to connect, and not your Flukso broker.

Kind regards,
Bert

**Comment by SamDeZwam** [comment]
Hi,

[home-assistant flukso 1.0.9.log](https://github.com/bertouttier/flukso-hacs/files/9794136/home-assistant.flukso.1.0.9.log)
[home-assistant Flukso 1.0.8.log](https://github.com/bertouttier/flukso-hacs/files/9794137/home-assistant.Flukso.1.0.8.log)
 Log files attached, I changed the ID's of the device and sensors.

Not sure what you mean by this:
" And could you also post the output of the following MQTT topics?"
     /device/+/test/tap
     /device/+/config/+

Kind regards,
Sam

**Comment by bollewolle** [comment]
Seems I have the same issue but logged it in the wrong repo (silly mne): https://github.com/flukso/hass_flukso_component/issues/5

Some logs can be found there as well.

**Comment by bollewolle** [comment]
So, I tried again today with the latest release 2022.12 and after the upgrade did the Flukso upgrade from 1.0.8 (the last working version for me) to 1.0.10. This time I had some errors due to the use of async_get_registry which seems to be depricated, so I added the following quick fixes to the code (checked some other integrations for reference).

In the __init.py__ file:
-  added "from homeassistant.helpers import device_registry as dr"
- commented "device_registry = await hass.helpers.device_registry.async_get_registry(hass)"
- added below that commented line "device_registry = dr.async_get(hass)"

After this I have no errors of any kind anymore, but even after serveral restarts, reboots and integration reloads I still get "undefined" in all of the sensors in the app.

With regards to your request:
> And could you also post the output of the following MQTT topics?
> ```
> /device/+/test/tap
> /device/+/config/+
> ```

For the config Topic there's only a sensor topic in it with the following information (I've replaced the last 8 characters of the id's with x's):
```
{"mqtt":{"bridge_restart_timeout":30,"bridge_address":"api.flukso.net","bridge_port":8883,"bridge_keepalive":60},"1":{"id":"786300f183e930a991c72b75xxxxxxxx","class":"analog","type":"electricity","counter":11284283,"function":"Electricity","port":[1,2,3],"enable":1,"rid":0,"current":50,"data_type":"counter","voltage":230},"main":{"reset_counters":0,"hw_minor":1,"max_sensors":6,"sw_major":1,"max_provisioned_sensors":13,"led_mode":256,"uart_tx_invert":0,"phase":3,"hw_major":2,"max_analog_sensors":3,"dsmr":2.2,"sw_minor":0,"uart_rx_invert":0},"3":{"id":"437453de575fb6e6e6206a52xxxxxxxx","class":"analog","counter":0,"enable":0,"current":50,"type":"electricity","voltage":230},"2":{"id":"d3c30d06c8002e6132a4ec94xxxxxxxx","class":"analog","counter":2,"enable":0,"current":50,"type":"electricity","voltage":230},"5":{"id":"5058b696beda910047f547fcxxxxxxxx","class":"pulse","port":[5],"type":"water","function":"Water Meter","enable":1,"constant":0.5,"rid":0,"data_type":"counter","counter":133464},"4":{"id":"018ef1b7f732a7730ff50a72xxxxxxxx","class":"pulse","type":"gas","function":"Gas Meter","port":[4],"constant":10,"rid":0,"enable":1,"data_type":"counter","counter":250},"7":{"id":"b536c1851e3dc736bcd40a5dxxxxxxxx"},"6":{"enable":0,"class":"uart","port":[6],"id":"be2e255e124eed3907ddaeb7xxxxxxxx","counter":0},"9":{"id":"63bddba10455501e8a71e954xxxxxxxx"},"8":{"id":"95ebf7176fbc9824da8f69f1xxxxxxxx"},"fsync":{"time":197,"exit_string":"successful","exit_status":0},"10":{"id":"ced6e55388fbfae0bc5a6a78xxxxxxxx"},"13":{"id":"bba4303e632fb028310fbf1bxxxxxxxx"},"12":{"id":"40bd70a83e7234f0f7031320xxxxxxxx"},"11":{"id":"6692a2a340d997ceabdcd961xxxxxxxx"},"daemon":{"upgrade_url":"http://www.flukso.net/files/upgrade/","enable_wan_branch":1,"cacert":"/etc/ssl/certs/flukso.ca.crt","enable_remote_upgrade":1,"enable_lan_branch":1,"wan_base_url":"https://api.flukso.net/","logmask":"info"}}
```

I cannot find any tap topic to be honest, not sure where I should see this. Note that the my Flukso model is the older FLM02A, with firmware version is 250.

If any additional information you might need, do let me know. I really would love to keep using my Flukso, I think I otherwise might have to start looking at alternative devices (I sure hope not).

**Comment by vk2him** [comment]
@bollewolle 

There are two methods to setup Flukso in Home Assistant - 1) Automated setup and 2) Manual setup. 

Bert's excellent HACS Integration does it automatically, however if you're having trouble then you can set it up manually by modifying the following code from my configuration.yaml 


This sets up sensors for Energy dashboard

```

  - platform: template
    sensors:
      exporting:
        friendly_name: "Current Energy Exporting"
        value_template: "{{ [0, (states('sensor.fluksoproduction') | float(0) - states('sensor.fluksoconsumption') | float(0))] | max }}"
        unit_of_measurement: "W"
        icon_template: mdi:flash

      importing:
        friendly_name: "Current Energy Importing"
        value_template: "{{ [0, (states('sensor.fluksoconsumption') | float(0)  - states('sensor.fluksoproduction') | float(0))] | max }}"
        unit_of_measurement: "W"
        icon_template: mdi:flash

      import_delta:
        friendly_name: "Current Energy Delta"
        value_template: "{{  (states('sensor.fluksoconsumption') | float(0)  - states('sensor.fluksoproduction') | float(0))  }}"
        unit_of_measurement: "W"
        icon_template: mdi:flash
      solarpower:
        friendly_name: "Solar Power"
        value_template: "{{ states('sensor.fluksoproduction')}}"
        unit_of_measurement: "W"
        icon_template: mdi:flash

sensor 10:
  - platform: integration
    source: sensor.solarpower
    name: energy_solar
    method: left
    #   unit: kWh
    unit_prefix: k
    unit_time: h
    round: 2
sensor 11:
  - platform: integration
    source: sensor.exporting
    name: energy_exporting
    method: left
    #    unit: kWh
    unit_prefix: k
    unit_time: h
    round: 2
sensor 12:
  - platform: integration
    source: sensor.importing
    name: energy_importing
    method: left
    #    unit: kWh
    unit_prefix: k
    unit_time: h
    round: 2
sensor 13:
  - platform: integration
    source: sensor.fluksoconsumption
    name: energy_using
    method: left
    #   unit: kWh
    unit_prefix: k
    unit_time: h
    round: 2
sensor 14:
  - platform: integration
    source: sensor.fluksoproduction
    name: energy_fluksosolar
    method: left
    #   unit: kWh
    unit_prefix: k
    unit_time: h
    round: 2

```


The following obtains mqtt data directly from your Flukso- be sure to replace xxxxxxxxx and yyyyyy with your flukso consumption/Solar topic identification numbers obtained from the flukso setup screen - here's my consumption as an example

![Image 001](https://user-images.githubusercontent.com/22878629/206578570-fea73812-a5d2-4ad1-aa89-c7a1c8f1fe75.jpg)


```


mqtt:
  sensor:
    - name: "fluksoconsumption"
      state_topic: "/sensor/xxxxxxxx/gauge"
      qos: 0
      unit_of_measurement: "W"
      value_template: "{{ value_json[1] }}"
      state_class: measurement
      device_class: power

    - name: "fluksoproduction"
      state_topic: "/sensor/yyyyyyyyyy/gauge"
      qos: 0
      unit_of_measurement: "W"
      value_template: '{% if is_state("sun.sun", "below_horizon")%}0{%else%}{{ value_json[1] }}{%endif%}'
      state_class: measurement
      device_class: power

```

You'll then have sensors that display your flukso data:

![Image 003](https://user-images.githubusercontent.com/22878629/206579697-2c6d2ad1-aad9-4bbf-8f74-50e43eb7642d.jpg)

Any you'll be able to use them in your Energy dashboard:

![Image 004](https://user-images.githubusercontent.com/22878629/206580060-ca68e822-0cc9-4a19-b14c-a7568e055421.jpg)

![Image 005](https://user-images.githubusercontent.com/22878629/206580098-e36bfb8c-7478-4fc9-82a2-7718c702da44.jpg)


If you want to display real-time per second data usage/production, install power-wheel-card from HACs and setup like this:

![Image 006](https://user-images.githubusercontent.com/22878629/206580922-0807cf8b-46e3-41d7-8daa-d21f803b47bd.jpg)
