### ISSUE TITLE
Issue with sensors created using the new mqtt integration key format

### ISSUE THREAD

**Issue by vk2him** [bertouttier/flukso-hacs#8]
The latest Home Assistant version 2022.6 introduced a new format for mqtt sensors. This Flukso add-on now produces the following warning in logs:

```
Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
```

As described in the documentation https://www.home-assistant.io/integrations/sensor.mqtt/#new_format, 

the previous method is now deprecated:

```
sensor:
  - platform: mqtt
    state_topic: "home/bedroom/temperature"
```

Can you update discovery.py to use the new method?

```
# Example configuration.yaml entry
mqtt:
  sensor:
    - state_topic: "home/bedroom/temperature"
 ```

Note - it will still work using the old method, however at some point the old method will cease to work in future HA releases.
Thanks
